### PR TITLE
Stylechange

### PR DESCRIPTION
**Pull request by awesomeamit1998**
Added black color and removed olive color.

### CODE REVIEW

**Comment by abhishalya** [comment]
@awesomeamit1998 Rebase please.

**Comment by abhishalya** [comment]
@awesomeamit1998 Follow this:

1. `git remote add upstream https://github.com/abhishalya/rating-image-generator.git`
2. `git fetch upstream`
3. `git rebase upstream/master`
4. `git commit --amend`
5. `git push origin branch-name`

**Comment by awesomeamit1998** [comment]
i guess its not working as it is saying unmerged files

**Comment by abhishalya** [comment]
@awesomeamit1998 Your branch is messed up. Do this exactly now:

```
git clone https://github.com/awesomeamit1998/rating-image-generator.git rig_dir
cd rig_dir
git checkout -b new_branch
git remote add upstream https://github.com/abhishalya/rating-image-generator.git
git fetch upstream
git rebase upstream/master
```
Now, do your changes, then:
```
git add .
git push origin new_branch
```
Create a PR from new_branch.

**Pull request closed without merging**
