### PR TITLE
Added colors to options

### PR DESCRIPTION
**Pull request by awesomeamit1998**
I have added color options to list

### CODE REVIEW

**Review by abhishalya — CHANGES_REQUESTED** [review]
Hi @awesomeamit1998 thanks for the contribution. The node_modules is not required here, could you remove than and amend the commit please.

Thanks! :)

**Comment by awesomeamit1998** [comment]
how to do that?

**Review by abhishalya — CHANGES_REQUESTED** [review]
@awesomeamit1998 

1. node_modules folder is automatically generated and should not be a part of your PR.
2. The colors represent the colors on the rating system. If you want to add a new color, you should add one which represents some rating for the user. So, you can add a color if it is on any of the programming site (and is used specifically for denoting the ratings of the user).

**Comment by awesomeamit1998** [comment]
i did not know  that lol.

**Comment by abhishalya** [comment]
Duplicate of https://github.com/abhishalya/rating-image-generator/pull/7

**Pull request closed without merging**
